package vista;

import com.mysql.cj.jdbc.Driver;
import vista.ListaEnlazada;
import java.sql.Statement;
import conexion.Conexion;
import controlador.CTRL_OrdenamientoInsercion;
import controlador.Ctrl_Producto;
import java.awt.Dimension;
import java.awt.TextField;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;

/**
 *
 * @author user
 */
public class InterGestionarProducto extends javax.swing.JInternalFrame {

    private int idProducto;
    int obtenerIdCategoriaCombo = 0;
    ListaEnlazada listaEnlazada;
    DefaultTableModel model;

    public InterGestionarProducto() {
        initComponents();
        this.setSize(new Dimension(900, 633));
        this.setTitle("Gestionar Productos");
        //Cargar la tabla
        this.CargarTablaProductos();
        this.CargarComboCategoria();

        //insertar imagen
        ImageIcon wallpaper = new ImageIcon("src/imagenes/Fondo15.png");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(900, 500, WIDTH));
        jLabel_wallpaper.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCantidad = new javax.swing.JLabel();
        lblCantidad1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_productos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton_vaciar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jButton_actualizar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        txt_descripcion3 = new javax.swing.JTextField();
        jComboBox_Igv = new javax.swing.JComboBox<>();
        jComboBox_categoria = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        txtBusqueda = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnOrdenar = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        lblCantidad.setDisplayedMnemonic('[');
        lblCantidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad.setText("Cantidad Elementos: ");

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCantidad1.setDisplayedMnemonic('[');
        lblCantidad1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCantidad1.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad1.setText("Cantidad Elementos: ");
        getContentPane().add(lblCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 220, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar Producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_productos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 730, 270));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_vaciar.setBackground(new java.awt.Color(51, 51, 255));
        jButton_vaciar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_vaciar.setText("Vaciar");
        jButton_vaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_vaciarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_vaciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, -1));

        jButton_eliminar.setBackground(new java.awt.Color(255, 51, 51));
        jButton_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, -1));

        jButton_actualizar1.setBackground(new java.awt.Color(51, 204, 0));
        jButton_actualizar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_actualizar1.setText("Actualizar");
        jButton_actualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_actualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 130, 270));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cantidad:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Precio:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Descripcion:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("IGV:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 90, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Categoria:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 90, -1));

        txt_cantidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_cantidad.setEnabled(false);
        jPanel3.add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 170, -1));

        txt_precio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 170, -1));

        txt_descripcion3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(txt_descripcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 170, -1));

        jComboBox_Igv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione IGV:", "No Grava IGV", "16%", "18%" }));
        jComboBox_Igv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_IgvActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox_Igv, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 150, -1));

        jComboBox_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Categoria:" }));
        jPanel3.add(jComboBox_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 150, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 870, 100));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BUSCAR", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 18))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setBackground(new java.awt.Color(51, 153, 255));
        btnBuscar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel4.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 110, 30));

        jComboBox2.setBackground(new java.awt.Color(242, 242, 242));
        jComboBox2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "POR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 14))); // NOI18N
        jPanel4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, 30));

        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        jPanel4.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 180, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 260, 160));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ORDENAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 18))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setBackground(new java.awt.Color(242, 242, 242));
        jComboBox1.setBorder(javax.swing.BorderFactory.createTitledBorder("POR"));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, 50));

        btnOrdenar.setBackground(new java.awt.Color(51, 153, 255));
        btnOrdenar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnOrdenar.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenar.setText("ORDENAR");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        jPanel5.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 30));

        jRadioButton3.setText("Codigo");
        jRadioButton3.setName("rdbAlumnos"); // NOI18N
        jPanel5.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jRadioButton5.setText("Precio");
        jRadioButton5.setName("rdbNotas"); // NOI18N
        jPanel5.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 260, 160));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_vaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_vaciarActionPerformed
        vaciarTablaProductos();
    }//GEN-LAST:event_jButton_vaciarActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed

        Ctrl_Producto controlProducto = new Ctrl_Producto();
        if (idProducto == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un producto");
        } else {
            if (!controlProducto.eliminar(idProducto)) {
                JOptionPane.showMessageDialog(null, "Producto eliminado");
                this.CargarTablaProductos();
                this.CargarComboCategoria();
                this.Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar");
            }
        }

    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jComboBox_IgvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_IgvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_IgvActionPerformed

    private void jButton_actualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_actualizar1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int codigoBusqueda = Integer.parseInt(txt_nombre.getText());

        // Llama al m�todo buscar de la lista enlazada
        Producto productoBuscado = listaEnlazada.buscar(codigoBusqueda);

        if (productoBuscado != null) {
            // Si se encontr� el producto, actualiza la tabla y selecciona la fila
            for (int i = 0; i < model.getRowCount(); i++) {
                int codigoTabla = (int) model.getValueAt(i, 0);
                if (codigoTabla == codigoBusqueda) {
                    jTable_productos.setRowSelectionInterval(i, i);
                    break;
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Producto no encontrado.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable_productos.getModel();

        int columnaOrdenamiento = jRadioButton3.isSelected() ? 0 : 1; // 0 para C�digo, 1 para Precio
        String ordenamientoSeleccionado = (String) jComboBox1.getSelectedItem(); // Usar jComboBox1 para seleccionar el tipo de ordenamiento

        List<Producto> productos = new ArrayList<>();

        // Recopilar datos de la tabla en funci�n de la selecci�n del usuario
        for (int i = 0; i < model.getRowCount(); i++) {
            int codigo = (int) model.getValueAt(i, 0);
            String descripcion = (String) model.getValueAt(i, 1);
            double precio = (double) model.getValueAt(i, 2);
//            productos.add(new Producto(codigo, descripcion, precio));
        }

        switch (ordenamientoSeleccionado) {
            case "Insercion" -> {
                if (columnaOrdenamiento == 0) {
                    // Ordenar por C�digo de producto
                    CTRL_OrdenamientoInsercion.ordenamientoInsercionCodigo(productos);
                } else {
                    // Ordenar por Precio
                    CTRL_OrdenamientoInsercion.ordenamientoInsercionCodigo(productos);
                }
                // Agregar m�s casos para otros tipos de ordenamiento si es necesario.
            }
            // Continuar con los dem�s casos para otros tipos de ordenamiento...
        }

        model.setRowCount(0);

        // Agregar filas ordenadas a la tabla
        for (Producto producto : productos) {
            model.addRow(new Object[]{producto.getIdProdcuto(), producto.getDescripcion(), producto.getPrecio()});
        }
    }//GEN-LAST:event_btnOrdenarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton jButton_actualizar1;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_vaciar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox_Igv;
    private javax.swing.JComboBox<String> jComboBox_categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton5;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_productos;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCantidad1;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_descripcion3;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables

//Metodo para limpiar
    private void Limpiar() {
        txt_nombre.setText("");
        txt_cantidad.setText("");
        txt_precio.setText("");
        txt_descripcion3.setText("");
        jComboBox_Igv.setSelectedItem("Seleccione IGV:");
        jComboBox_categoria.setSelectedItem("Seleccione Categoria:");
    }

//Metodo para cargar las categorias en el JComboBox   
    private void CargarComboCategoria() {
        Connection cn = Conexion.conectar();
        String sql = "select * from tb_categoria";
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_categoria.removeAllItems();
            jComboBox_categoria.addItem("Seleccione Categoria:");
            while (rs.next()) {
                jComboBox_categoria.addItem(rs.getString("descripcion"));
            }
            cn.close();
        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(null, "Error al carga las categorias");
            System.out.println("Error al carga las categorias");
        }
    }

    //Metodo para mostrar todas los productos registrados
    String descripcionCategoria = "";
    double precio = 0.0;
    int porcentajeIgv = 0;
    double IGV = 0;

    private void CargarTablaProductos() {
        Connection con = Conexion.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "select p.idProducto, p.nombre, p.cantidad, p.precio, p.descripcion, p.porcentajeIgv, c.descripcion, p.estado from tb_producto As p, tb_categoria As c where p.idCategoria = c.idCategoria;";
        Statement st;

        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            InterGestionarProducto.jTable_productos = new JTable(model);
            InterGestionarProducto.jScrollPane1.setViewportView(InterGestionarProducto.jTable_productos);

            model.addColumn("Nro.º");//ID
            model.addColumn("Nombre");
            model.addColumn("Cantidad");
            model.addColumn("Precio");
            model.addColumn("Descripcion");
            model.addColumn("Igv");
            model.addColumn("Categoria");
            model.addColumn("estado");

            while (rs.next()) {

                precio = rs.getDouble("precio");
                porcentajeIgv = rs.getInt("porcentajeIgv");

                Object fila[] = new Object[8];

                for (int i = 0; i < 8; i++) {

                    if (i == 5) {
                        this.calcularIgv(precio, porcentajeIgv);
                        fila[i] = IGV;
                        rs.getObject(i + 1);
                    } else {
                        fila[i] = rs.getObject(i + 1);
                    }

                }
                model.addRow(fila);
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error en llenado de tabla productos: " + e);
        }
        //evento que permite obtener el campo al que da click el usuario
        jTable_productos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_productos.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idProducto = (int) model.getValueAt(fila_point, columna_point);
                    EnviarDatosProductoSeleccionado(idProducto);
                }
            }
        });
    }

    //Calculamos IGV
    private double calcularIgv(double precio, int igv) {

        int p_igv = igv;

        switch (p_igv) {
            case 0:
                IGV = 0.0;
                break;
            case 16:
                IGV = precio * 0.16;
                break;
            case 18:
                IGV = precio * 0.18;
                break;
            default:
                break;
        }
        //Redondeamos Decimales
        IGV = (double) Math.round(IGV * 100) / 100;

        return IGV;
    }

    //metodo que envia los datos seleccionados
    private void EnviarDatosProductoSeleccionado(int idProducto) {
        try {
            Connection con = Conexion.conectar();
            PreparedStatement pst = con.prepareStatement(
                    "select * from tb_producto where idProducto = '" + idProducto + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_nombre.setText(rs.getString("nombre"));
                txt_cantidad.setText(rs.getString("cantidad"));
                txt_precio.setText(rs.getString("precio"));
                txt_descripcion3.setText(rs.getString("descripcion"));
                int igv = rs.getInt("porcentajeIgv");
                switch (igv) {
                    case 0:
                        jComboBox_Igv.setSelectedItem("No Grava IGV");
                        break;
                    case 16:
                        jComboBox_Igv.setSelectedItem("16%");
                        break;
                    case 18:
                        jComboBox_Igv.setSelectedItem("18%");
                        break;
                    default:
                        jComboBox_Igv.setSelectedItem("Seleccione IGV:");
                        break;
                }
                int idCate = rs.getInt("idCategoria");
                jComboBox_categoria.setSelectedItem(relacionarCategoria(idCate));
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error en la seleccion de producto: " + e);
        }

    }

    //Metodo para reacionar categoria
    private String relacionarCategoria(int idCategoria) {

        String sql = "select descripcion from tb_categoria where idCategoria = '" + idCategoria + "'";
        Statement st;
        try {
            Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                descripcionCategoria = rs.getString("descripcion");
            }
            cn.close();
        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(null, "Error al carga las categorias");
            System.out.println("Error al obtener el id de la categoria");
        }
        return descripcionCategoria;
    }

    //Metodo para obtener id de la categoria
    private int IdCategoria() {
        String sql = "select * from tb_categoria where descripcion = '" + this.jComboBox_categoria.getSelectedItem() + "'";
        Statement st;
        try {
            Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                obtenerIdCategoriaCombo = rs.getInt("idCategoria");
            }
        } catch (SQLException e) {
            System.out.println("Eror al Obtener ID de la Categoria");
        }
        return obtenerIdCategoriaCombo;
    }

//    private void Vaciar(JTable tabla){
//        String sql="DELETE FROM tabla tb_producto WHERE id = ? '" + this.jButton_vaciar;
//        Statement st;
//        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
//        try {
//            for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
//            modelo.removeRow(i);
//        }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "No Se puede Eliminiar Los Productos");
//        }
//    }
    public void vaciarTablaProductos() {
        String sql = "delete from  tb_producto";
        Statement st;

        try {
            Connection conexion = Conexion.conectar();
            st = conexion.createStatement();
            st.executeUpdate(sql);
            conexion.close();
            JOptionPane.showMessageDialog(null, "Tabla Vaciada");
        } catch (SQLException e) {
            System.out.println("Error al vaciar la tabla de productos");
            e.printStackTrace();
        }
        this.CargarTablaProductos();
    }

    //
    public static void mostrarCantidadElementos(String databaseName, String tableName, JLabel lblCantidad1) {
    // Obtener el número de elementos
    int cantidadElementos = getCantidadElementos(databaseName, tableName);

    // Mostrar el número de elementos
    lblCantidad1.setText(String.valueOf(cantidadElementos));
}

private static int getCantidadElementos(String databaseName, String tableName) {
    // Obtener la consulta para contar el número de elementos
    String consulta = "SELECT COUNT(*) AS cantidad "
            + "FROM `bd_sistema_ventas`.` tb_productos`;";
    // Ejecutar la consulta
    Connection conexion = null;
    Statement sentencia = null;
    ResultSet resultado = null;
    try {
        conexion = Conexion.conectar();
        sentencia = conexion.createStatement();
        resultado = sentencia.executeQuery(consulta);

        // Obtener el número de elementos
        if (resultado.next()) {
            return resultado.getInt("cantidad");
        } else {
            return 0;
        }
    } catch (SQLException e) {
        e.printStackTrace();
        return -1;
    } finally {
        try {
            if (resultado != null) {
                resultado.close();
            }
            if (sentencia != null) {
                sentencia.close();
            }
            if (conexion != null) {
                conexion.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}


    //
//    public int getCantidadElementos() {
//        // Obtener la consulta para contar el número de elementos
//        String consulta = "SELECT COUNT(*) AS cantidad FROM  tb_productos ";
//
//        // Ejecutar la consulta
//        Connection conexion = null;
//        Statement sentencia = null;
//        ResultSet resultado = null;
//        try {
//            conexion = Conexion.conectar();
//            sentencia = conexion.createStatement();
//            resultado = sentencia.executeQuery(consulta);
//
//            // Obtener el número de elementos
//            if (resultado.next()) {
//                return resultado.getInt("cantidad");
//            } else {
//                return 0;
//            }
//        } catch (SQLException e) {
//            e.printStackTrace();
//            return -1;
//        } finally {
//            try {
//                if (resultado != null) {
//                    resultado.close();
//                }
//                if (sentencia != null) {
//                    sentencia.close();
//                }
//                if (conexion != null) {
//                    conexion.close();
//                }
//            } catch (SQLException e) {
//                e.printStackTrace();
//            }
//        }
//    }

}
