package vista;

import conexion.Conexion;
import controlador.Ctrl_Producto;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import modelo.Producto;

/**
 *
 * @author user
 */
public class InterProducto extends javax.swing.JInternalFrame {

    int obtenerIdCategoriaCombo = 0;

    public InterProducto() {
        initComponents();
        this.setSize(400,300);
        this.setTitle("Nuevo Producto");
        this.CargarComboCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxt_nombre = new javax.swing.JTextField();
        jtxt_cantidad = new javax.swing.JTextField();
        jtxt_precio = new javax.swing.JTextField();
        jtxt_descripcion = new javax.swing.JTextField();
        jComboBox_igv = new javax.swing.JComboBox<>();
        jComboBox_categoria = new javax.swing.JComboBox<>();
        jButton_guardar = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo Producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 90, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Cantidad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Precio:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Descripcion:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 90, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("IGV:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 90, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Categorias:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, -1));

        jtxt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(jtxt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 170, -1));

        jtxt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_cantidadActionPerformed(evt);
            }
        });
        getContentPane().add(jtxt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 170, -1));

        jtxt_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_precioActionPerformed(evt);
            }
        });
        getContentPane().add(jtxt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, -1));

        jtxt_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_descripcionActionPerformed(evt);
            }
        });
        getContentPane().add(jtxt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 170, -1));

        jComboBox_igv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione IGV:", "No Grava IGV", "16%", "18%" }));
        jComboBox_igv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_igvActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_igv, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 170, -1));

        jComboBox_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Categoria:" }));
        getContentPane().add(jComboBox_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 170, -1));

        jButton_guardar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_guardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_guardar.setText("Guardar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 90, 30));

        jLabel_wallpaper.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo13.png"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nombreActionPerformed

    private void jtxt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_cantidadActionPerformed

    private void jtxt_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_precioActionPerformed

    private void jtxt_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_descripcionActionPerformed

    private void jComboBox_igvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_igvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_igvActionPerformed

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        //
        Producto producto = new Producto();
        Ctrl_Producto controlProducto = new Ctrl_Producto();
        //
        String igv = "";
        String categoria = "";
        igv = jComboBox_igv.getSelectedItem().toString().trim();
        categoria = jComboBox_categoria.getSelectedItem().toString().trim();

        //Validacion de campos
        if (jtxt_nombre.getText().equals("") || jtxt_cantidad.getText().equals("") || jtxt_precio.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Complete Todos los Campos");
            jtxt_nombre.setBackground(Color.red);
            jtxt_cantidad.setBackground(Color.red);
            jtxt_precio.setBackground(Color.red);
        } else {
            //Consulta si el producto ya esta registrado
            if (!controlProducto.existeProdcuto(jtxt_nombre.getText().trim())) {
                if (igv.equalsIgnoreCase("Seleccione IGV:")) {
                    JOptionPane.showMessageDialog(null, "Seleccione IGV.");
                } else {
                    if (categoria.equalsIgnoreCase("Seleccione Categoria:")) {
                        JOptionPane.showMessageDialog(null, "Seleccione categoria.");
                    } else {
                        try {
                            producto.setNombre(jtxt_nombre.getText().trim());
                            producto.setCatidad(Integer.parseInt(jtxt_cantidad.getText().trim()));
                            String PRECIOTXT = "";
                            double Precio = 0.0;
                            PRECIOTXT = jtxt_precio.getText().trim();
                            boolean aux = false;
                            /*
                            *Si el usuario ingresa "," como punto decimal lo transformamos a punto "."
                             */
                            for (int i = 0; i < PRECIOTXT.length(); i++) {
                                if (PRECIOTXT.charAt(i) == ',') {
                                    String PrecioNuevo = PRECIOTXT.replace(",", ".");
                                    Precio = Double.parseDouble(PrecioNuevo);
                                    aux = true;
                                }
                            }
                            //Evaluar las condiciones
                            if (aux == true) {
                                producto.setPrecio(Precio);
                            } else {
                                Precio = Double.parseDouble(PRECIOTXT);
                                producto.setPrecio(Precio);
                            }
                            producto.setDescripcion(jtxt_descripcion.getText().trim());
                            //porcentaje igv
                            if (igv.equalsIgnoreCase("No Grava IGV")) {
                                producto.setPorcentajeIgv(0);
                            } else if (igv.equalsIgnoreCase("16%")) {
                                producto.setPorcentajeIgv(16);
                            } else if (igv.equalsIgnoreCase("18%")) {
                                producto.setPorcentajeIgv(18);
                            }
                            //idCategoria - cargar un metodopara obtener el id de la categoria
                            this.IdCategoria();
                            producto.setIdCategoria(obtenerIdCategoriaCombo);
                            producto.setEstado(1);
                            if (controlProducto.guardar(producto)) {
                                JOptionPane.showMessageDialog(null, "Registro Guardado");
                                jtxt_nombre.setBackground(Color.green);
                                jtxt_cantidad.setBackground(Color.green);
                                jtxt_precio.setBackground(Color.green);
                                jtxt_descripcion.setBackground(Color.green);
                                this.CargarComboCategorias();
                                this.jComboBox_igv.setSelectedItem("Seleccione IGV:");
                                this.Limpiar();
                            } else {
                                JOptionPane.showMessageDialog(null, "Error al Guardar");
                            }
                        } catch (HeadlessException | NumberFormatException e) {
                            System.out.println("Error en:" + e);
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "El Producto Existe en la Bade de Datos");
            }
        }
    }//GEN-LAST:event_jButton_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JComboBox<String> jComboBox_categoria;
    private javax.swing.JComboBox<String> jComboBox_igv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JTextField jtxt_cantidad;
    private javax.swing.JTextField jtxt_descripcion;
    private javax.swing.JTextField jtxt_nombre;
    private javax.swing.JTextField jtxt_precio;
    // End of variables declaration//GEN-END:variables

    //Metodos Auxiliares
    //Meotodo para limpiar los campos
    private void Limpiar() {
        jtxt_nombre.setText("");
        jtxt_cantidad.setText("");
        jtxt_precio.setText("");
        jtxt_descripcion.setText("");
    }

    //Metodos para cargar categorias
    private void CargarComboCategorias() {
        Connection cn = Conexion.conectar();
        String sql = "select * from tb_categoria";
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_categoria.removeAllItems();
            jComboBox_categoria.addItem("Seleccione Categoria:");
            while (rs.next()) {
                jComboBox_categoria.addItem(rs.getString("descripcion"));
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Erro al Cargar Categorias");
        }
    }

    //Metodo para obtener id de la categoria
    private int IdCategoria() {
        String sql = "select * from tb_categoria where descripcion = '" + this.jComboBox_categoria.getSelectedItem() + "'";
        Statement st;
        try {
            Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                obtenerIdCategoriaCombo = rs.getInt("idCategoria");
            }
        } catch (SQLException e) {
            System.out.println("Eror al Obtener ID de la Categoria");
        }
        return obtenerIdCategoriaCombo;
    }
}
