package vista;

import java.awt.Dimension;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import conexion.Conexion;
import controlador.Ctrl_RegistrarVenta;
import controlador.Venta_PDF;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.CabeceraVenta;
import modelo.DetalleVenta;

/**
 *
 * @author user
 */
public class InterFacturacion extends javax.swing.JInternalFrame {

    //modelo tabla
    private DefaultTableModel modelodatosProductos;
    //lista detalle venta
    ArrayList<DetalleVenta> listaProductos = new ArrayList<>();
    private DetalleVenta producto;
    //
    private int idCliente = 0;
    //
    private int idProducto = 0;
    private String nombre = "";
    private int cantidadProductos = 0;
    private double precioUnidad = 0.0;
    private int porcentajeIgv = 0;
    //
    private int cantidad = 0;
    private double subTotal = 0.0;
    private double descuento = 0.0;
    private double igv = 0.0;
    private double totalPagar = 0.0;
    //
    private double subtotalgeneral = 0.0;
    private double descuentogeneral = 0.0;
    private double igvgeneral = 0.0;
    private double totalpagargeneral = 0.0;

    //
    private int auxIdDetalle = 1;

    public InterFacturacion() {
        initComponents();

        this.setSize(new Dimension(800, 600));
        this.setTitle("Nueva Venta");
        //carga cliente
        this.CargarClientes();
        //carga producto
        this.CargarProductos();
        //cargar modelo tabla
        this.inicarTablaProducto();
        //desabilitar sin producto
        txt_efectivo.setEnabled(false);
        jButton_calcularcambio.setEnabled(false);

        txt_subtotal.setText("0.0");
        txt_igv.setText("0.0");
        txt_descuento.setText("0.0");
        txt_totalpagar.setText("0.0");
        //insertar imagen
        ImageIcon wallpaper = new ImageIcon("src/imagenes/F25.png");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(800, 600, WIDTH));
        jLabel_wallpaper.setIcon(icono);
        this.repaint();
    }
//Cargar tabla con produtos

    private void inicarTablaProducto() {
        modelodatosProductos = new DefaultTableModel();
        //añadir columnas
        modelodatosProductos.addColumn("N.º");
        modelodatosProductos.addColumn("Nombre");
        modelodatosProductos.addColumn("Cantidad");
        modelodatosProductos.addColumn("P. Unitario");
        modelodatosProductos.addColumn("SubTotal");
        modelodatosProductos.addColumn("Descuento");
        modelodatosProductos.addColumn("IGV");
        modelodatosProductos.addColumn("Total a Pagar");
        modelodatosProductos.addColumn("Accion");
        //agregar datos del modelo a la tabla
        this.jTable_productos.setModel(modelodatosProductos);
    }
//presentamos los productos en la tabla

    private void ListaTablaProductos() {
        this.modelodatosProductos.setRowCount(listaProductos.size());
        for (int i = 0; i < listaProductos.size(); i++) {
            this.modelodatosProductos.setValueAt(i + 1, i, 0);
            this.modelodatosProductos.setValueAt(listaProductos.get(i).getNombre(), i, 1);
            this.modelodatosProductos.setValueAt(listaProductos.get(i).getCantidad(), i, 2);
            this.modelodatosProductos.setValueAt(listaProductos.get(i).getPreciounitario(), i, 3);
            this.modelodatosProductos.setValueAt(listaProductos.get(i).getSubtotal(), i, 4);
            this.modelodatosProductos.setValueAt(listaProductos.get(i).getDescuento(), i, 5);
            this.modelodatosProductos.setValueAt(listaProductos.get(i).getIgv(), i, 6);
            this.modelodatosProductos.setValueAt(listaProductos.get(i).getTotalpagar(), i, 7);
            this.modelodatosProductos.setValueAt("Eliminar", i, 8);//implemento boton eliminar
        }
        //añade jtable
        jTable_productos.setModel(modelodatosProductos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_cliente = new javax.swing.JComboBox<>();
        jComboBox_producto = new javax.swing.JComboBox<>();
        txt_buscar_cliente = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        jButton_buscar_cliente = new javax.swing.JButton();
        jButton_añadir_producto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_productos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_subtotal = new javax.swing.JTextField();
        txt_descuento = new javax.swing.JTextField();
        txt_igv = new javax.swing.JTextField();
        txt_totalpagar = new javax.swing.JTextField();
        txt_efectivo = new javax.swing.JTextField();
        txt_cambio = new javax.swing.JTextField();
        jButton_calcularcambio = new javax.swing.JButton();
        jButton_RegistarVENTA = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NUEVA VENTA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Cliente:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Producto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cantidad:");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 80, -1));

        jComboBox_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Cliente:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 170, -1));

        jComboBox_producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Producto:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 170, -1));
        jComboBox_producto.getAccessibleContext().setAccessibleName("");

        getContentPane().add(txt_buscar_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 150, -1));
        getContentPane().add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 60, -1));

        jButton_buscar_cliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_buscar_cliente.setText("BUSCAR");
        jButton_buscar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscar_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_buscar_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 80, -1));

        jButton_añadir_producto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_añadir_producto.setText("AÑADIR");
        jButton_añadir_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_añadir_productoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_añadir_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 80, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_productosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_productos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 740, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 760, 210));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("SubTotal:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Descuento:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("IGV:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Total a Pagar:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Efectivo:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 145, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Cambio:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 175, -1, -1));

        txt_subtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_subtotal.setEnabled(false);
        jPanel2.add(txt_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 120, -1));

        txt_descuento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_descuento.setEnabled(false);
        jPanel2.add(txt_descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 120, -1));

        txt_igv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_igv.setEnabled(false);
        jPanel2.add(txt_igv, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 120, -1));

        txt_totalpagar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_totalpagar.setEnabled(false);
        jPanel2.add(txt_totalpagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 120, -1));

        txt_efectivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(txt_efectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 145, 120, -1));

        txt_cambio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_cambio.setEnabled(false);
        jPanel2.add(txt_cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 175, 120, -1));

        jButton_calcularcambio.setBackground(new java.awt.Color(21, 255, 255));
        jButton_calcularcambio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_calcularcambio.setText("CALCULAR CAMBIO");
        jButton_calcularcambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calcularcambioActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_calcularcambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 145, 140, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 380, 210));

        jButton_RegistarVENTA.setBackground(new java.awt.Color(255, 51, 51));
        jButton_RegistarVENTA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_RegistarVENTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/impresora.png"))); // NOI18N
        jButton_RegistarVENTA.setText("REGISTRAR VENTA");
        jButton_RegistarVENTA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_RegistarVENTA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_RegistarVENTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistarVENTAActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_RegistarVENTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 170, 100));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_buscar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscar_clienteActionPerformed
        String buscarcliente = txt_buscar_cliente.getText().trim();
        Connection cn = Conexion.conectar();
        String sql = "select nombre, apellido from tb_cliente where dni = '" + buscarcliente + "'";
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                jComboBox_cliente.setSelectedItem(rs.getString("nombre") + " " + rs.getString("apellido"));
            } else {
                jComboBox_cliente.setSelectedItem("Seleccione Cliente:");
                JOptionPane.showMessageDialog(null, "DNI INCORRECTO O NO ENCONTRADO");
            }
            txt_buscar_cliente.setText("");
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al Buscar Cliente" + e);
        }
    }//GEN-LAST:event_jButton_buscar_clienteActionPerformed

    private void jButton_añadir_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_añadir_productoActionPerformed
        String combo = this.jComboBox_producto.getSelectedItem().toString();
        //validar que seleccione un producto
        if (combo.equalsIgnoreCase("Seleccione producto:")) {
            JOptionPane.showMessageDialog(null, "Seleccione un producto");
        } else {
            //validar que ingrese una cantidad
            if (!txt_cantidad.getText().isEmpty()) {
                //validar que el usuario no ingrese caracteres no numericos
                boolean validacion = validar(txt_cantidad.getText());
                if (validacion == true) {
                    //validar que la cantidad sea mayor a cero
                    if (Integer.parseInt(txt_cantidad.getText()) > 0) {
                        cantidad = Integer.parseInt(txt_cantidad.getText());
                        //ejecutar metodo para obtener datos del producto
                        this.DatosProducto();
                        //validar que la cantidad de productos seleccionado no sea mayor al stock de la base de datos
                        if (cantidad <= cantidadProductos) {

                            subTotal = precioUnidad * cantidad;
                            totalPagar = subTotal + igv + descuento;

                            //redondear decimales
                            subTotal = (double) Math.round(subTotal * 100) / 100;
                            igv = (double) Math.round(igv * 100) / 100;
                            descuento = (double) Math.round(descuento * 100) / 100;
                            totalPagar = (double) Math.round(totalPagar * 100) / 100;

                            //se crea un nuevo producto
                            producto = new DetalleVenta(auxIdDetalle,//idDetalleVenta
                                    1, //idCabecera
                                    idProducto,
                                    nombre,
                                    Integer.parseInt(txt_cantidad.getText()),
                                    precioUnidad,
                                    subTotal,
                                    descuento,
                                    igv,
                                    totalPagar,
                                    1//estado
                            );
                            //añadir a la lista
                            listaProductos.add(producto);
                            JOptionPane.showMessageDialog(null, "Producto Agregado");
                            auxIdDetalle++;
                            txt_cantidad.setText("");//limpiar el campo
                            //volver a cargar combo productos
                            this.CargarProductos();
                            this.CalcularTotalPagar();
                            txt_efectivo.setEnabled(true);
                            jButton_calcularcambio.setEnabled(true);

                        } else {
                            JOptionPane.showMessageDialog(null, "La cantidad supera el Stock");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Ingrese una Cantidad Mayor a 0");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No se Admite Caracteres no Numericos");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingresa la cantidad de productos");
            }
        }
        //llamar al metodo
        this.ListaTablaProductos();
    }//GEN-LAST:event_jButton_añadir_productoActionPerformed

    private void jButton_calcularcambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calcularcambioActionPerformed
        if (!txt_efectivo.getText().isEmpty()) {
            //validamos que el usuario no ingrese otros caracteres no numericos 
            boolean validacion = validarDouble(txt_efectivo.getText());
            if (validacion == true) {
                //validar que el efectivo sea mayor a cero
                double efc = Double.parseDouble(txt_efectivo.getText().trim());
                double top = Double.parseDouble(txt_totalpagar.getText().trim());

                if (efc < top) {
                    JOptionPane.showMessageDialog(null, "Dinero Insuficiente");
                } else {
                    double cambio = (efc - top);
                    double cambi = (double) Math.round(cambio * 100d) / 100;
                    String camb = String.valueOf(cambi);
                    txt_cambio.setText(camb);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No se Admite Caracteres no Numericos");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese el Dinero para Calcular el Cambio");
        }
    }//GEN-LAST:event_jButton_calcularcambioActionPerformed
    int idArrayList = 0;
    private void jTable_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_productosMouseClicked
        int fila_point = jTable_productos.rowAtPoint(evt.getPoint());
        int columna_point = 0;
        //
        if (fila_point > -1) {
            idArrayList = (int) modelodatosProductos.getValueAt(fila_point, columna_point);
        }
        //
        int opcion = JOptionPane.showConfirmDialog(null, "Desea Eliminar el Producto");
        //opciones de confirmar = (si = 0; no = 1; cancel = 2; close = -1;)
        switch (opcion) {
            case 0:
                listaProductos.remove(idArrayList - 1);
                this.CalcularTotalPagar();
                this.ListaTablaProductos();
                break;
            case 1:
                break;
            default:
                break;
        }

    }//GEN-LAST:event_jTable_productosMouseClicked

    private void jButton_RegistarVENTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistarVENTAActionPerformed
        CabeceraVenta cabeceraVenta = new CabeceraVenta();
        DetalleVenta detalleVenta = new DetalleVenta();
        Ctrl_RegistrarVenta controlVenta = new Ctrl_RegistrarVenta();

        String FechaActual = "";
        Date date = new Date();
        FechaActual = new SimpleDateFormat("yyyy/MM/dd").format(date);
        //
        if (!jComboBox_cliente.getSelectedItem().equals("Seleccione Cliente:")) {
            if (listaProductos.size() > 0) {
                //metodo para obtener id cliente
                this.ObtenerIdCliente();
                //Registrar cabecera
                cabeceraVenta.setIdCabeceraventa(0);
                cabeceraVenta.setIdCliente(idCliente);
                cabeceraVenta.setValorPago(Double.parseDouble(txt_totalpagar.getText()));
                cabeceraVenta.setFechaVenta(FechaActual);
                cabeceraVenta.setEstado(1);
                //
                if (controlVenta.guardar(cabeceraVenta)) {
                    JOptionPane.showMessageDialog(null, "Venta Registrada Exitosamente");
                    //generamos la factura
                    Venta_PDF pdf = new Venta_PDF();
                    pdf.DatosClientes(idCliente);
                    pdf.GenerarFactura();
                    //guardar detalle
                    for (DetalleVenta elemento : listaProductos) {
                        detalleVenta.setIdDetalleVenta(0);
                        detalleVenta.setIdCabeceraVenta(0);
                        detalleVenta.setIdProducto(elemento.getIdProducto());
                        detalleVenta.setCantidad(elemento.getCantidad());
                        detalleVenta.setPreciounitario(elemento.getPreciounitario());
                        detalleVenta.setSubtotal(elemento.getSubtotal());
                        detalleVenta.setDescuento(elemento.getDescuento());
                        detalleVenta.setIgv(elemento.getIgv());
                        detalleVenta.setTotalpagar(elemento.getTotalpagar());
                        detalleVenta.setEstado(1);
                        //
                        if (controlVenta.guardarDetalle(detalleVenta)) {
                            //System.out.println("Detalle Guardado Exitosamente");
                            txt_subtotal.setText("0.0");
                            txt_igv.setText("0.0");
                            txt_descuento.setText("0.0");
                            txt_totalpagar.setText("0.0");
                            txt_efectivo.setText("0.0");
                            txt_cambio.setText("0.0");
                            auxIdDetalle = 1;
                            //
                            this.CargarClientes();
                            this.RestarStockProductos(elemento.getIdProducto(), elemento.getCantidad());
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al Guardar Detalle de la Venta");
                        }
                    }
                    //vacioamos la lista
                    listaProductos.clear();
                    ListaTablaProductos();
                } else {
                    JOptionPane.showMessageDialog(null, "No se Guardo la Cabecera de Venta");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un Producto");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un Cliente");
        }
    }//GEN-LAST:event_jButton_RegistarVENTAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_RegistarVENTA;
    private javax.swing.JButton jButton_añadir_producto;
    private javax.swing.JButton jButton_buscar_cliente;
    private javax.swing.JButton jButton_calcularcambio;
    private javax.swing.JComboBox<String> jComboBox_cliente;
    private javax.swing.JComboBox<String> jComboBox_producto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_productos;
    private javax.swing.JTextField txt_buscar_cliente;
    private javax.swing.JTextField txt_cambio;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_descuento;
    private javax.swing.JTextField txt_efectivo;
    private javax.swing.JTextField txt_igv;
    private javax.swing.JTextField txt_subtotal;
    public static javax.swing.JTextField txt_totalpagar;
    // End of variables declaration//GEN-END:variables

//Cargar Clientes en combo
    private void CargarClientes() {
        Connection cn = Conexion.conectar();
        String sql = "select * from tb_cliente";
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_cliente.removeAllItems();
            jComboBox_cliente.addItem("Seleccione Cliente:");
            while (rs.next()) {
                jComboBox_cliente.addItem(rs.getString("nombre") + " " + rs.getString("apellido"));
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al Cargar Clientes" + e);
        }
    }
//Cargar productos en combo

    private void CargarProductos() {
        Connection cn = Conexion.conectar();
        String sql = "select * from tb_producto";
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_producto.removeAllItems();
            jComboBox_producto.addItem("Seleccione Producto:");
            while (rs.next()) {
                jComboBox_producto.addItem(rs.getString("nombre"));
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al Cargar Productos" + e);
        }
    }
//corregir insercion de caracteres

    private boolean validar(String valor) {
        try {
            int num = Integer.parseInt(valor);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
//mostrar datos de producto

    private void DatosProducto() {
        try {
            String sql = "select * from tb_producto where nombre = '" + this.jComboBox_producto.getSelectedItem() + "'";
            Connection cn = Conexion.conectar();
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                idProducto = rs.getInt("idProducto");
                nombre = rs.getString("nombre");
                cantidadProductos = rs.getInt("cantidad");
                precioUnidad = rs.getDouble("precio");
                porcentajeIgv = rs.getInt("porcentajeIgv");
                this.CalcularIgv(precioUnidad, porcentajeIgv);
            }
        } catch (SQLException e) {
            System.out.println("Error al Obtener Datos del Producto" + e);
        }
    }
//metodo calcular igv

    private double CalcularIgv(double precio, int porcentajeIgv) {
        int p_igv = porcentajeIgv;

        switch (p_igv) {
            case 0:
                igv = 0.0;
                break;
            case 16:
                igv = (precio * cantidad) * 0.16;
                break;
            case 18:
                igv = (precio * cantidad) * 0.18;
                break;
            default:
                break;
        }
        return igv;
    }
//calculamos el pago total

    private void CalcularTotalPagar() {
        subtotalgeneral = 0;
        descuentogeneral = 0;
        igvgeneral = 0;
        totalpagargeneral = 0;
        //
        for (DetalleVenta elemento : listaProductos) {
            subtotalgeneral += elemento.getSubtotal();
            descuentogeneral += elemento.getDescuento();
            igvgeneral += elemento.getIgv();
            totalpagargeneral += elemento.getTotalpagar();
        }
        //redondeo decimales
        subtotalgeneral = (double) Math.round(subtotalgeneral * 100) / 100;
        igvgeneral = (double) Math.round(igvgeneral * 100) / 100;
        descuentogeneral = (double) Math.round(descuentogeneral * 100) / 100;
        totalpagargeneral = (double) Math.round(totalpagargeneral * 100) / 100;
        //enviamos datos
        txt_subtotal.setText(String.valueOf(subtotalgeneral));
        txt_igv.setText(String.valueOf(igvgeneral));
        txt_descuento.setText(String.valueOf(descuentogeneral));
        txt_totalpagar.setText(String.valueOf(totalpagargeneral));
    }
//validar cambio

    private boolean validarDouble(String valor) {
        try {
            double num = Double.parseDouble(valor);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
//ObtenerIdCliente

    private void ObtenerIdCliente() {
        try {
            String sql = "select * from tb_cliente where concat(nombre, ' ' ,apellido) = '" + this.jComboBox_cliente.getSelectedItem() + "'";
            Connection cn = Conexion.conectar();
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                idCliente = rs.getInt("idCliente");
            }
        } catch (SQLException e) {
            System.out.println("Error al Obtener Id del Cliente:" + e);
        }
    }

//metodo para restar el stock
    private void RestarStockProductos(int idProducto, int cantidad) {
        int cantidadProductosStock = 0;
        try {
            Connection cn = Conexion.conectar();
            String sql = "select idProducto, cantidad from tb_producto where idProducto ='" + idProducto + "'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            //
            while (rs.next()) {
                cantidadProductosStock = rs.getInt("cantidad");
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al restar Cantidad" + e);
        }
        //
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement consulta = cn.prepareStatement("update tb_producto set cantidad=? where idProducto = '" + idProducto + "'");
            int cantidadNueva = cantidadProductosStock - cantidad;
            consulta.setInt(1, cantidadNueva);
            if (consulta.executeUpdate() > 0) {
//                System.out.println("Se Actualizo Correctamente");
            }
            cn.close();
        } catch (SQLException e) {
//            System.out.println("Error al restar Cantidad 2" + e);
        }
    }
}
